### ISSUE TITLE
No SSH username given, tried to open terminal - uncaught exception

### ISSUE THREAD

**Issue by elegantandrogyne** [adafruit/Adafruit-Pi-Finder#58]
Test case: I want to get to the login shell (so no username - will enter it later).

1. Run the Pi Finder, scan for Raspberries
2. Choose the IP address
3. Clear the "Username" and "Password" boxes
4. Click "Terminal".

I got:
`Uncaught Exception:
Error: Invalid username
    at Client.connect (/tmp/mozilla_elegant0/linux-x64/resources/app/node_modules/adafruit-pi-finder/node_modules/ssh2/lib/client.js:130:11)
    at new ssh (/tmp/mozilla_elegant0/linux-x64/resources/app/node_modules/adafruit-pi-finder/ssh.js:31:12)
    at ssh (/tmp/mozilla_elegant0/linux-x64/resources/app/node_modules/adafruit-pi-finder/ssh.js:20:12)
    at ssh_connect (/tmp/mozilla_elegant0/linux-x64/resources/app/node_modules/adafruit-pi-finder/main.js:110:13)
    at EventEmitter.<anonymous> (/tmp/mozilla_elegant0/linux-x64/resources/app/node_modules/adafruit-pi-finder/main.js:81:5)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/tmp/mozilla_elegant0/linux-x64/resources/atom.asar/browser/api/lib/web-contents.js:91:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)`

Using 64-bit Linux build on Debian stretch/sid amd64.

**Comment by SalvorinFex** [comment]
Well, I'd imagine that if I tried to use Pi Finder in an unintended way I could find tons of issues too.
